name: CI with selenium testng

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ allure_steps ]

    jobs:
      build:
        runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v3
          with:
            java-version: '17'

        - run:  mvn clean test -DsuiteXmlFile=test.xml
