name: Run Selenium Tests

on:
  push:
    branches: [ main, allure_steps ]
  pull_request:
    branches: [ main, allure_steps ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set CHROME_BIN path
        run: echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV

      - name: Build project
        run: mvn clean compile

      - name: Run tests
        run: mvn test

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports
