name: Run Tests with Allure

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Устанавливаем Allure через apt
      - name: Install Allure Commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      # 4. Кешируем зависимости Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 5. Запускаем тесты с помощью Maven
      - name: Run Tests
        run: mvn clean test
        continue-on-error: true  # Позволяет продолжить выполнение даже при ошибках тестов

      # 6. Генерируем отчет Allure
      - name: Generate Allure Report
        run: allure generate target/allure-results --clean -o target/allure-report

      # 7. Загрузка отчета Allure
      - name: Upload Allure report
        if: always()  # Этот шаг выполнится всегда, независимо от того, прошли ли тесты
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report  # Публикуем отчет Allure
